server:
  port: 8888

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/course?useSSL=false&serverTimezone=GMT
    username: root
    password: root123456

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*